name: Hello GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Print Host Information
        run: |
          echo "Hello from Self Hosted Runner!"
          hostname
          pwd
          whoami
          uname -a

      - name: Git Version
        run: git --version

      - name: Terraform Version
        run: terraform version

      - name: Docker Version
        run: docker --version

      - name: Kubectl Version
        run: kubectl version --client

      - name: Azure CLI Version
        run: az version